function R = lunar_ablation(opts)
%LUNAR_ABLATION  Monte Carlo comparison of all trackers over many seeds, with 95% Wilson intervals.
%   R = lunar_ablation                                  % boulders + polar, 20 seeds x 600 s, toolbox included
%   R = lunar_ablation(Seeds=1:5, Seconds=300)          % quicker
%   Writes results.md next to this file. "ID kept 1-5 s": of the people who were tracked, hid for 1-5 s and came
%   back, the share that came back with the same track ID (the headline number of the web lab).
arguments
    opts.Scenarios (1,:) string = ["boulders" "polar"]
    opts.Seeds (1,:) double = 1:20
    opts.Seconds (1,1) double = 600
    opts.Toolbox (1,1) string = "both"
    opts.Save (1,1) string = ""          % save raw per-tracker tallies to a .mat (for parallel runs; merge with lunar_ablation_merge)
end
lines = ["# MATLAB results: tracking through occlusion", "", ...
    sprintf("%d seeds x %g s per scenario. Generated by `lunar_ablation.m` on %s.", numel(opts.Seeds), opts.Seconds, string(datetime('today'))), ""];
R = struct();
for sc = opts.Scenarios
    acc = [];
    for sd = opts.Seeds
        s = LunarSession(sc, sd, Toolbox=opts.Toolbox); s.run(opts.Seconds);
        for k = 1:numel(s.runs)
            m = s.runs(k).metrics.summary(); b = m.occByDuration(1:2);
            acc(k).name = s.runs(k).tracker.name; %#ok<AGROW>
            if sd == opts.Seeds(1), acc(k).kept = 0; acc(k).n = 0; acc(k).idsw = []; acc(k).idf1 = []; end
            acc(k).kept = acc(k).kept + sum([b.kept]); acc(k).n = acc(k).n + sum([b.n]);
            acc(k).idsw(end+1) = m.idsw; acc(k).idf1(end+1) = m.idf1;
        end
        fprintf('%s seed %d done\n', sc, sd);
    end
    lines(end+1:end+4) = [sprintf("## %s", LunarWorld.scenarios().(char(sc)).label), "", ...
        "| Tracker | ID kept 1-5 s (95% CI) | ID switches per run | IDF1 |", "|---|---|---|---|"];
    for k = 1:numel(acc)
        [lo, hi] = wilson(acc(k).kept, acc(k).n);
        lines(end+1) = sprintf("| %s | %.0f%% (%.0f-%.0f%%), %d/%d | %.1f | %.3f |", acc(k).name, 100*acc(k).kept/max(acc(k).n, 1), ...
            100*lo, 100*hi, acc(k).kept, acc(k).n, mean(acc(k).idsw), mean(acc(k).idf1)); %#ok<AGROW>
    end
    lines(end+1) = ""; R.(char(sc)) = acc;
end
if opts.Save ~= "", save(opts.Save, 'R', 'opts'); return; end
writelines(lines, fullfile(fileparts(mfilename('fullpath')), 'results.md'));
fprintf('%s\n', strjoin(lines, newline));
end
function [lo, hi] = wilson(k, n)
if n == 0, lo = NaN; hi = NaN; return; end
z = 1.96; p = k/n; d = 1 + z^2/n; c = (p + z^2/(2*n))/d; h = z*sqrt(p*(1-p)/n + z^2/(4*n^2))/d;
lo = c - h; hi = c + h;
end
