function lunar_ablation_merge(files, seconds)
%LUNAR_ABLATION_MERGE  Combine .mat files saved by parallel lunar_ablation(Save=...) runs into results.md.
%   lunar_ablation_merge(["part1.mat" "part2.mat"], 600)
all = struct(); nSeeds = struct();
for f = files
    d = load(f); sc = fieldnames(d.R);
    for i = 1:numel(sc)
        s = sc{i}; a = d.R.(s);
        if ~isfield(all, s), all.(s) = a; nSeeds.(s) = numel(d.opts.Seeds); continue; end
        nSeeds.(s) = nSeeds.(s) + numel(d.opts.Seeds);
        for k = 1:numel(a)
            all.(s)(k).kept = all.(s)(k).kept + a(k).kept; all.(s)(k).n = all.(s)(k).n + a(k).n;
            all.(s)(k).idsw = [all.(s)(k).idsw a(k).idsw]; all.(s)(k).idf1 = [all.(s)(k).idf1 a(k).idf1];
        end
    end
end
lines = ["# MATLAB results: tracking through occlusion", "", sprintf("Generated by `lunar_ablation.m` on %s, %g s per run.", string(datetime('today')), seconds), ...
    "\"ID kept 1-5 s\": of the people who were tracked, hid for 1-5 s and came back, the share that came back with the same ID.", ""];
sc = fieldnames(all);
for i = 1:numel(sc)
    acc = all.(sc{i});
    lines(end+1:end+4) = [sprintf("## %s (%d seeds)", LunarWorld.scenarios().(sc{i}).label, nSeeds.(sc{i})), "", ...
        "| Tracker | ID kept 1-5 s (95% CI) | ID switches per run | IDF1 |", "|---|---|---|---|"];
    for k = 1:numel(acc)
        [lo, hi] = wilson(acc(k).kept, acc(k).n);
        lines(end+1) = sprintf("| %s | %.0f%% (%.0f-%.0f%%), %d/%d | %.1f | %.3f |", acc(k).name, 100*acc(k).kept/max(acc(k).n, 1), ...
            100*lo, 100*hi, acc(k).kept, acc(k).n, mean(acc(k).idsw), mean(acc(k).idf1)); %#ok<AGROW>
    end
    lines(end+1) = "";
end
writelines(lines, fullfile(fileparts(mfilename('fullpath')), 'results.md'));
fprintf('%s\n', strjoin(lines, newline));
end
function [lo, hi] = wilson(k, n)
if n == 0, lo = NaN; hi = NaN; return; end
z = 1.96; p = k/n; d = 1 + z^2/n; c = (p + z^2/(2*n))/d; h = z*sqrt(p*(1-p)/n + z^2/(4*n^2))/d;
lo = c - h; hi = c + h;
end
